### ISSUE TITLE
Plugin error "The server factory could not be located for the given input: Microsoft.Owin.Host.HttpListener"

### ISSUE THREAD

**Issue by DoomsDay007** [TroyFernandes/MusicBeeChromecast#9]
Hi,

Thank you so much for your efforts with the plugin. I'm getting an error when I try to use the program. I went through the setup and everything seemed to be okay, but when I went to connect to my Chromecast I received the following error:

"The server factory could not be located for the given input: Microsoft.Owin.Host.HttpListener"

Followed by another error:

"Error starting the webserver. Webserver exception"

The word Musicbee shows up on the on the TV but nothing plays. Any ideas? Thank you so much for your help.

**Comment by TroyFernandes** [comment]
You'll get that issue if the ``Microsoft.Owin.Host.HttpListener.dll`` is missing in the plugins folder.

Do you have both the ``mb_Chromecast.dll`` and the ``Microsoft.Owin.Host.HttpListener.dll`` in the plugins folder? You can find both those .dlls in the zipped file

**Comment by DoomsDay007** [comment]
Yes, I copied both into the mb_Chromecast.dll and Microsoft.Owin.Host.HttpListener.dll in the plugins folder, and they are both there.

**Comment by TroyFernandes** [comment]
I think i'm narrowing this issue down more. 

Could you try this and tell me if it fixes it for you?

Move the ``Microsoft.Owin.Host.HttpListener.dll`` from the musicbee plugins folder to the musicbee main directory (i.e put the .dll where the main ``MusicBee.exe`` is. Up one folder). Only keep one copy of the .dll

If the above doesn't work for you, try the same as above but copy instead of move the .dll. So keep two copies.

**Comment by DoomsDay007** [comment]
I tried both move (one copy of the .dll) and copy (two copies of the .dll, one in each folder), and neither way worked.

I also just thought to mention that I am using the Microsoft Store version of MusicBee if that makes a difference. Sorry for not mentioning it before.

**Comment by DoomsDay007** [comment]
I have made some progress. It was indeed an issue with it being the Microsoft Store version of MusicBee. I had to add `Microsoft.Owin.Host.HttpListener.dll` to the folder for the Windows Store version of MusicBee located at `C:\Program Files\WindowsApps\50072StevenMayall.MusicBee_3.3.7.0_x86__kcr266et74avj\win32\Plugins` and also the `win32` folder (up one folder level) where the `MusicBee.exe` is located like you mentioned. And I'll tell you what, it was a pain in the butt copying them to that folder because Windows wouldn't give me access permissions to copy them there no matter how I changed permission settings. To get it done, I had to boot a live Linux session from a flash drive and copy it using the file explorer there. But I got'er done lol.
So that got rid of the `The server factory could not be located for the given input: Microsoft.Owin.Host.HttpListener` and `Error starting the webserver. Webserver exception` errors.
Now the track information shows up on my TV when I play a song. However, I do not have any sound coming out of my TV when I play a song, so this presents a new problem. Any ideas on how to address this? Thank you again for your help.

**Comment by TroyFernandes** [comment]
Interesting, I would've not guessed that it being the windows store version would make a difference, but glad that part of the issue is solved now. 

The no sound part is a common issue and most likely the issue is with your firewall and/or router. You can try taking a look at these and maybe it might help you:

- [Troubleshooting section](https://github.com/TroyFernandes/MusicBeeChromecast#troubleshooting)
- [Issue someone else had](https://getmusicbee.com/forum/index.php?topic=30467.msg182962#msg182962)
- [Example setup vid](https://streamable.com/i7d27h)

Let me know if any of this helps
